apiVersion: v1
kind: BuildConfig
metadata:
  name: jws-app
  labels:
    app: generic-java-jenkins-pipeline
    application: jws-app
    template: generic-java-jenkins-pipeline
spec:
  triggers: []
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jboss-webserver30-tomcat8-openshift:1.2'
  output:
    to:
      kind: ImageStreamTag
      name: 'jws-app:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 2
