apiVersion: v1
kind: BuildConfig
metadata:
  name: my-app
  labels:
    app: my-app
    application: my-app
    template: generic-my-app
spec:
  triggers: []
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jboss-webserver30-tomcat8-openshift:1.2'
  output:
    to:
      kind: "DockerImage"
      name: "docker-registry.default.svc:5000/myimages/myimage:tag"
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 2
