apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: 2017-11-06T19:42:58Z
  labels:
    name: openshift-jee-sample
  name: openshift-jee-sample
  namespace: my-eap
  resourceVersion: "614684"
  selfLink: /oapi/v1/namespaces/my-eap/buildconfigs/openshift-jee-sample
  uid: b115a190-c32a-11e7-99b8-5254007ae7cc
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        try {
           timeout(time: 20, unit: 'MINUTES') {
              def appName="openshift-jee-sample"
              def project=""

              node {
                stage("Initialize") {
                  project = env.PROJECT_NAME
                }
              }

             node("maven") {
                stage("Checkout") {
                  git url: "https://github.com/openshift/openshift-jee-sample.git", branch: "master"
                }
                stage("Build WAR") {
                  sh "mvn clean package -Popenshift"
                  stash name:"war", includes:"target/ROOT.war"
                }
              }

              node {
                stage("Build Image") {
                  unstash name:"war"
                  sh "oc start-build ${appName}-docker --from-file=target/ROOT.war -n ${project}"
                  openshiftVerifyBuild bldCfg: "${appName}-docker", namespace: project, waitTime: '20', waitUnit: 'min'
                }
                stage("Deploy") {
                  openshiftDeploy deploymentConfig: appName, namespace: project
                }
              }
           }
        } catch (err) {
           echo "in catch block"
           echo "Caught: ${err}"
           currentBuild.result = 'FAILURE'
           throw err
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: 18w4uHT4FKAtAWw3nGJp4AKCWcpYGJWYc5N2JXUs
    type: GitHub
  - generic:
      secret: N7Wull0moIRxkw02PdbS4lXkPxnsQ4VFCIG5kWrd

